import pytest
from {{ service_name }} import app

# TODO: Autogenerated


class Test{{ service_name }}(object):

    @classmethod
    def setup_class(cls):
        pass

    def test_something(self):
        pass

    @classmethod
    def teardown_class(cls):
        pass
