The {{ service_name }} Service for Portal3
----------------

### TODO: Autogenerated README

#### Quick Start

   
**Run the {{ service_name }} docker container**
```bash
// Build the image
$ docker build -t cdnetworks/{{ service_name }} .
// Start the container with default conf
$ docker run -p 8080:8080 cdnetworks/{{ service_name }}
// Start the container with manual conf (refer Configuration)
$ docker run -p 8080:8080 -e "SERVICE_CONFIG_PATH=/config/config.py" -v /home/cdnw/p3/{{ service_name }}/config/config.py:/config/config.py p3/{{ service_name }}
```
   
##### Install manually:   
 
**Configure the {{ service_name }} Service**  
Edit the `{{ service_name }}/config/config.py`  
TODO: Document Proper Config
  
  
**Install the dependency and flask app**  
```bash
// Install only dependency for development
$ make install-dev
// or install the flask app
$ make install
```
  
  
**Overwrite the Configuration**   
```bash
// Define new configuration
$ nano /tmp/{{ service_name }}_config.py
/////////////////////////////
DEBUG = False
TODO: Document Proper Config
/////////////////////////////

// set SERVICE_CONFIG_PATH to provide config file
$ export SERVICE_CONFIG_PATH=/tmp/{{ service_name }}_config.py
```
  
  
**Spin the Flask App**  
```bash
// Start the flask app by running
$ {{ service_name }}-service`
// Or to start manually
$ python server.py
```
